### ISSUE TITLE
[Laravel 9] Call to undefined function [...] array_get() / array_set()

### ISSUE THREAD

**Issue by Petemir** [janiskelemen/laravel-setting#12]
**Describe the bug**
Hello! Thank you for the useful package. I tried to use it on Laravel 9.8.1, but I hit some problems. Neither `Setting::get(key)` nor `Setting::set(key, value)` seem to work when I have a multi-level array. 

**To Reproduce**
1. Install the package (`composer require ...`)
2. Publish the configuration (`php artisan vendor:publish ...`)
3. Try to get/set any Setting value
4. Get error "Call to undefined function [...] array_get" or "Call to undefined function [...] array_set"

**Expected behavior**

**Additional context**
array_get / array_set helper functions have been deprecated since (I think) Laravel 6, so they aren't available any more. This is fixed doing the following:

In `vendor\janiskelemen\laravel-setting\src\Setting.php`:
* Import Illuminate\Support\Arr:
`use Illuminate\Support\Arr`
* Replace array_get in line 336 by:
`$setting = Arr::get($setting, $subkey);`
* Replace array_set in line 351 by:
`Arr::set($setting, $subkey, $new_value);`

I don't do a PR as probably this would break support for older Laravel versions.

**Comment by Petemir** [comment]
Other deprecated functions: array_forget, array_key_exists...

**Comment by janiskelemen** [comment]
Hi @Petemir, thanks for pointing this out. I haven't been able to fully test it on Laravel 9.8.1, but I would really appreciate a PR. I will then tag it with a new major version with the info that older versions of Laravel are not supported by that release.

**Comment by janiskelemen** [comment]
@Petemir Fixed with version 2.0.0

**Comment by Petemir** [comment]
Sorry, got caught with easter break and correcting midterms. Thanks for the fix!
