### ISSUE TITLE
[Feature Request] Laravel 10/11 Support

### ISSUE THREAD

**Issue by Petemir** [janiskelemen/laravel-setting#15]
Hello!

I'd like to know if support for Laravel 10 or 11 planned? 

Just as an fyi, I cloned the repo locally, updated the composer.json requirements (to support phpunit/phpunit 10, and illuminate/support 10), updated my composer.json to add this local repo, and the package seems to work (for Laravel 10). I didn't do any extensive testing, I just checked that changed settings got correctly updated on my database, and it seemed to be that way. Therefore, perhaps for L10 the upgrade is "easy" (no idea about L11, though).

Thanks in advance!

**Comment by janiskelemen** [comment]
Hi, no changes were needed for Laravel 10 & 11, so I updated the repo to support both.

**Comment by Petemir** [comment]
That was quick. Thanks! 😄 .
